[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[from-internal]
exten => 1001,1,Dial(PJSIP/1001,30)
 same => n,Hangup()

exten => 1002,1,Dial(PJSIP/1002,30)
 same => n,Hangup()

exten => 9999,1,Answer()
 same => n,Stasis(ari-app)
 same => n,Hangup()

[from-external]
